services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true
