services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./client:/app
      - /app/node_modules
    # Commented out until front end needs .env
    #env_file:
    #  - ./client/.env
    stdin_open: true
    tty: true
