const verifyJwt = require('../utils/verifyJwt');

const token = 'eyJraWQiOiJKUnJJVTIra1pGNERDU3MxcUowOVhxbnNPUHRibzVMYmZvR21FRVNJM3lJPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiZXZGZHNvaXp2Wk1acTVKTW1rSDhnZyIsInN1YiI6IjMxN2JhNTMwLTIwNDEtNzAwNS05M2Y1LTY4ZmM1Nzg0M2VjZiIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0yLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMl9nQlhBVk1YVUsiLCJjb2duaXRvOnVzZXJuYW1lIjoiMzE3YmE1MzAtMjA0MS03MDA1LTkzZjUtNjhmYzU3ODQzZWNmIiwiYXVkIjoiM205dXR0cDgyZ2dmOGd1NjJsbTEyZWE3ajYiLCJldmVudF9pZCI6IjZjZDdhZTQ0LWE2MjItNDhiNS1iOGVkLWI0YzlkZTQ5OWFlZSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzUxMzE3NTgyLCJleHAiOjE3NTEzMjExODIsImlhdCI6MTc1MTMxNzU4MiwianRpIjoiMWQxNTgyMjgtNTllMy00ZTU1LWIzYmUtMTYyN2I2NjhkMzZiIiwiZW1haWwiOiJwcmFuYXZzdWJiaWFoQGdtYWlsLmNvbSJ9.QdqxEJhY2ZDjygztnaJku_eKA_mauTsFTKbLewEBuwWT6ub4B91gzcUYvV0UqSwWjoKU0e9nddj5dQRUgQnYouh4zjBr5mU50fSdYBJDzDBk6dSqdb_EZb71cLNRvsJpwAMy5S-k_2orEVt3XZtFKm8iZS5jZtEBmL1iX4e3boEMV022SoaoVzYmraJfHRN1s_9lQtllKGkPxYwCfmjauAG2twgxGrQGAaNLY72qTC8Uodti_PmsCMiAWXuLyrMZAAfWA5noRBh43fAdp_eSj_FDd7V0G0sYvesmdNb2PLCCBO2GkNGdKPS84a0zyGKThPRz9gtaj43KG8bUKEVDZQ';

verifyJwt(token)
  .then(decoded => {
    console.log('Token verified successfully!');
    console.log('Decoded payload:', decoded);
  })
  .catch(err => {
    console.error('Token verification failed:', err.message);
  });
