const verifyJwt = require("../utils/verifyJwt");
const authController = require("../controllers/authController");

const token =
  "eyJraWQiOiJKUnJJVTIra1pGNERDU3MxcUowOVhxbnNPUHRibzVMYmZvR21FRVNJM3lJPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI5MTZiMjU3MC0zMGMxLTcwODUtNmIwNC0xYmIxZTRiOGVjZmQiLCJjb2duaXRvOmdyb3VwcyI6WyJwYXRpZW50cyJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0yLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMl9nQlhBVk1YVUsiLCJjb2duaXRvOnVzZXJuYW1lIjoiOTE2YjI1NzAtMzBjMS03MDg1LTZiMDQtMWJiMWU0YjhlY2ZkIiwib3JpZ2luX2p0aSI6Ijg1OTY0Y2NkLTNkYzYtNDNlMS1iMzE1LWZhMzA2ZTVjZGQyMCIsImF1ZCI6IjNtOXV0dHA4MmdnZjhndTYybG0xMmVhN2o2IiwiZXZlbnRfaWQiOiI0YjA4ZTJkOS02NDUzLTQ2M2EtYTZiYS1kZmMxZDRmM2JkOTkiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTc1Mzg1MDg1MCwiZXhwIjoxNzUzODU0NDUwLCJpYXQiOjE3NTM4NTA4NTAsImp0aSI6IjY1YTRkYzMxLTc3YmUtNDMzMi05YWMzLWFkNDg2MmVhNTFiNiIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20ifQ.L5nwtHrKWRD0rVToeaxxFNjJSLskeOrzTH2wNZJ5uQ1p82CF9LoOGQcoeFau9G2oK4hRoFCD8frjJGVDugAz92WiCjJoocz7_OAVKeVgyW-UZMjq-enAz-pXuvyQqJJrGHvWkETPhHlqU1xggrLTsgc7nqHydqyES_66EXKtNsVW1uZpiBFrrcaFc-RohhYL4Z3arkTPNhzn42s-iFjsjOBrWkA1GE8OSPybbmXxplpxs27TUW19oQVn1yuzh49wKhK0lds4nebAw91JBfyWLql7KnNbk1PQYihpzo8iQe_9wvaQXdgZpsh73wrVLq7tQG7BFYqe0tvMb1Z3QZVOsw";

verifyJwt(token)
  .then((decoded) => {
    console.log("Token verified successfully!");
    console.log("Decoded payload:", decoded);
  })
  .catch((err) => {
    console.error("Token verification failed:", err.message);
  });
