import { createTheme } from '@mantine/core';

/**
 * 🎨 CENTRALIZED THEME CONFIGURATION
 * ===================================
 * 
 * This file controls ALL colors, gradients, shadows, and styling across the entire application.
 * 
 * 🔥 BENEFITS FOR FRONTEND TEAM:
 * - Single source of truth for all colors
 * - Easy theme switching (light/dark mode ready)
 * - Consistent design system
 * - CSS variables auto-generated by Mantine
 * - Component-level styling overrides
 * 
 * 🎯 USAGE:
 * - In JSX: c="brand.6" or gradient={{ from: 'brand.4', to: 'accent.6' }}
 * - In CSS: var(--mantine-color-brand-6) or var(--mantine-color-accent-5)
 * - Custom variables: var(--gradient-hero) or var(--shadow-card)
 */

export const theme = createTheme({
  // 🎨 Primary color used throughout the app
  primaryColor: 'brand',
  
  // 🎨 Default color scheme
  defaultColorScheme: 'light',
  
  // 📝 Typography settings
  fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif',
  fontFamilyMonospace: 'Monaco, Courier, monospace',
  headings: {
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif',
    fontWeight: '600',
  },
  
  // 🌈 CUSTOM COLOR PALETTE
  colors: {
    // Primary brand colors (minty pastel green)
    brand: [
      '#f0fdf9', // brand.0 - lightest mint cream
      '#e6fffa', // brand.1 - very light mint
      '#d1fae5', // brand.2 - light mint
      '#a7f3d0', // brand.3 - soft mint
      '#6ee7b7', // brand.4 - medium mint
      '#34d399', // brand.5 - vibrant mint
      '#10b981', // brand.6 - primary mint (default)
      '#059669', // brand.7 - darker mint
      '#047857', // brand.8 - deep mint
      '#065f46', // brand.9 - darkest mint
    ],
    
    // Accent colors (reddish brown)
    accent: [
      '#fdf8f6', // accent.0 - lightest cream
      '#f4e6d9', // accent.1 - light cream
      '#e8ccb3', // accent.2 - warm beige
      '#d4a574', // accent.3 - light brown
      '#bc8a5f', // accent.4 - medium brown
      '#a0522d', // accent.5 - sienna brown
      '#8b4513', // accent.6 - saddle brown (primary)
      '#704214', // accent.7 - dark brown
      '#4a2c0e', // accent.8 - darker brown
      '#2d1b09', // accent.9 - darkest brown
    ],
    
    // Action colors (for CTAs and important buttons)
    action: [
      '#fff5f5', // action.0 - lightest
      '#fed7d7', // action.1
      '#feb2b2', // action.2
      '#fc8181', // action.3
      '#f56565', // action.4
      '#ff6b6b', // action.5 - primary action
      '#ee5a24', // action.6 - default action
      '#e53e3e', // action.7
      '#c53030', // action.8
      '#9b2c2c', // action.9 - darkest
    ],
    
    // Success colors
    success: [
      '#f0fff4', // success.0
      '#c6f6d5', // success.1
      '#9ae6b4', // success.2
      '#68d391', // success.3
      '#48bb78', // success.4
      '#38a169', // success.5
      '#2f855a', // success.6 - default success
      '#276749', // success.7
      '#22543d', // success.8
      '#1a202c', // success.9
    ],
  },

  // 🎨 CUSTOM CSS VARIABLES (accessible via var(--variable-name))
  other: {
    // Gradient definitions
    gradients: {
      primary: 'linear-gradient(135deg, #34d399 0%, #8b4513 100%)',
      hero: 'linear-gradient(135deg, #6ee7b7 0%, #10b981 60%, #a0522d 100%)',
      cta: 'linear-gradient(45deg, #ff6b6b, #ee5a24)',
      features: 'linear-gradient(135deg, #faf8f5 0%, #f5f2ed 100%)',
      testimonials: 'linear-gradient(135deg, #f5f2ed 0%, #ede7dd 100%)',
    },
    
    // Shadow definitions
    shadows: {
      card: '0 4px 12px rgba(139, 69, 19, 0.1)', // subtle brown shadow
      cardHover: '0 8px 25px rgba(139, 69, 19, 0.15)', // brown shadow on hover
      button: '0 4px 14px rgba(34, 197, 94, 0.15)', // mint green button shadow
      buttonHover: '0 8px 20px rgba(34, 197, 94, 0.25)', // stronger mint shadow
      actionButton: '0 10px 25px rgba(255, 107, 107, 0.3)',
    },
    
    // Text colors
    text: {
      primary: '#2e2e2e',
      secondary: '#495057',
      muted: '#6c757d',
      light: '#adb5bd',
    },
    
    // Background colors
    backgrounds: {
      primary: '#faf8f5', // creamy eggshell
      secondary: '#f5f2ed', // slightly darker eggshell
      tertiary: '#ede7dd', // warm beige
      dark: '#2e2e2e',
    },
  },

  // 🎯 COMPONENT-LEVEL STYLING OVERRIDES
  components: {
    // Button component styling
    Button: {
      defaultProps: {
        size: 'md',
      },
      styles: (theme) => ({
        root: {
          // Gradient button variant
          '&[data-variant="gradient"]': {
            background: 'var(--gradient-primary)',
            border: 'none',
            transition: 'all 0.3s ease',
            '&:hover': {
              transform: 'translateY(-2px)',
              boxShadow: 'var(--shadow-button-hover)',
            },
          },
          
          // Action button variant (for CTAs)
          '&[data-variant="action"]': {
            background: 'var(--gradient-cta)',
            border: 'none',
            color: 'white',
            fontWeight: 600,
            transition: 'all 0.3s ease',
            '&:hover': {
              transform: 'translateY(-2px)',
              boxShadow: 'var(--shadow-action-button)',
            },
          },
        },
      }),
    },

    // Container component defaults
    Container: {
      defaultProps: {
        size: 'xl',
      },
    },

    // Paper component styling
    Paper: {
      styles: (theme) => ({
        root: {
          backgroundColor: 'var(--bg-primary)',
          boxShadow: 'var(--shadow-card)',
          transition: 'all 0.3s ease',
          '&:hover': {
            boxShadow: 'var(--shadow-card-hover)',
            transform: 'translateY(-2px)',
          },
        },
      }),
    },

    // Title component styling
    Title: {
      styles: (theme) => ({
        root: {
          color: 'var(--mantine-color-accent-6)',
          '&[data-order="1"]': {
            fontSize: '3.5rem',
            fontWeight: 900,
            lineHeight: 1.1,
            '@media (max-width: 768px)': {
              fontSize: '2.5rem',
            },
          },
          '&[data-order="2"]': {
            fontSize: '2.5rem',
            fontWeight: 700,
            '@media (max-width: 768px)': {
              fontSize: '2rem',
            },
          },
        },
      }),
    },

    // Text component styling
    Text: {
      styles: (theme) => ({
        root: {
          color: 'var(--mantine-color-accent-6)',
          '&[data-size="xl"]': {
            fontSize: '1.25rem',
            lineHeight: 1.6,
            '@media (max-width: 768px)': {
              fontSize: '1.125rem',
            },
          },
        },
      }),
    },
  },

  // 📱 Responsive breakpoints
  breakpoints: {
    xs: '30em',
    sm: '48em', 
    md: '64em',
    lg: '74em',
    xl: '90em',
  },

  // 🎨 CSS Variables injection - Fixed implementation
  cssVariablesResolver: (theme) => ({
    variables: {
      // Inject custom gradients as CSS variables
      '--gradient-primary': theme.other.gradients.primary,
      '--gradient-hero': theme.other.gradients.hero,
      '--gradient-cta': theme.other.gradients.cta,
      '--gradient-features': theme.other.gradients.features,
      '--gradient-testimonials': theme.other.gradients.testimonials,
      
      // Inject custom shadows as CSS variables
      '--shadow-card': theme.other.shadows.card,
      '--shadow-card-hover': theme.other.shadows.cardHover,
      '--shadow-button': theme.other.shadows.button,
      '--shadow-button-hover': theme.other.shadows.buttonHover,
      '--shadow-action-button': theme.other.shadows.actionButton,
      
      // Inject text colors as CSS variables
      '--text-primary': theme.other.text.primary,
      '--text-secondary': theme.other.text.secondary,
      '--text-muted': theme.other.text.muted,
      '--text-light': theme.other.text.light,
      
      // Inject background colors as CSS variables
      '--bg-primary': theme.other.backgrounds.primary,
      '--bg-secondary': theme.other.backgrounds.secondary,
      '--bg-tertiary': theme.other.backgrounds.tertiary,
      '--bg-dark': theme.other.backgrounds.dark,
    },
    light: {
      // Light theme specific variables - repeat important ones
      '--bg-primary': theme.other.backgrounds.primary,
      '--bg-secondary': theme.other.backgrounds.secondary,
      '--bg-tertiary': theme.other.backgrounds.tertiary,
      '--text-primary': theme.other.text.primary,
      '--text-secondary': theme.other.text.secondary,
    },
    dark: {
      // Dark theme specific variables (for future dark mode)
      '--text-primary': '#ffffff',
      '--text-secondary': '#e9ecef',
      '--bg-primary': '#2e2e2e',
      '--bg-secondary': '#495057',
      '--bg-tertiary': '#495057',
      '--bg-dark': '#1a1a1a',
    },
  }),
});
